
services:
  frontend:
    build: PlatformFrontend
    ports:
      - 5173:5173
    volumes:
        - ./PlatformFrontend:/code:ro
  backend:
    build: platformbackend
    ports:
      - 3001:3001
    volumes:
       - ./platformbackend:/code:rw
    env_file:
      - .env
    networks:
        - serverside
  database:
    image: postgres:12-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
        - serverside
    volumes:
      - db-data:/var/lib/postgresql/data



networks:
  serverside:
volumes:
  db-data: 