services:
  front:
    build: frontend/
    container_name: frontend
    ports:
      - 80:80
    networks:
      app:
    restart: always

  back:
    build: backend/
    container_name: backend
    ports:
      - 3001:3001
    env_file:
      - .env
    networks:
      app:
    restart: always

networks:
  app: