
services:
  frontend:
    build: PlatformFrontend
    ports:
      - 80:80
    volumes:
        - ./PlatformFrontend:/code:rw
  backend:
    build: platformbackend
    ports:
      - 3001:3001
      - 5555:5555
    volumes:
       - ./platformbackend:/code:rw
    env_file:
      - .env
    networks:
        - serverside
networks:
  serverside:
